language: node_js

node_js:
  - '0.12'

addons:
  apt:
    packages:
    - graphicsmagick
env:
  NODE_ENV: 'test'

after_success:
  - NODE_ENV=test LOG_LV=info node_modules/.bin/istanbul cover node_modules/.bin/_mocha -- -u exports -R spec test/bootstrap.js test/**/*.test.js --timeout 20000
